### ISSUE TITLE
Multiple rate implementation

### ISSUE THREAD

**Issue by saleho27** [lfriends/java-installment-loan-calculator#1]
Can you please add feature of multiple interest?

For example the tenour is 15 years, in the first three years the interest rate is 3% then for 4th and 5th the rate is 4% and lastly the 6th till 15th year the interest rate is 5%

Thanks before

**Comment by lfriends** [comment]
you mean changing the interest rate while having the same installment value for the whole plan? ... sound quite complicated.

**Comment by saleho27** [comment]
> you mean changing the interest rate while having the same installment value for the whole plan? ... sound quite complicated.

No, the installment offcourse will be different...

So in my question, there will be 3 monthly installment and they are not the same

Many banks in my country use this method to attract customers, so they give fixed rate (it can be first 3 years, first 2 years, and some next years, before using floating rate in the rest)

The floating rate offcourse we don't know, because it happens in the future

But we can assume the floating in next some years till end off installment based on floating rate right now (usually 11% - 13%) depends on National Bank
